config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

# класс "Ограничение". М-д "matches" принимает запрос, который был отправлен
# на адрес '/sidekiq'. Приходит на этот адрес запрос, перенаправлем в AdminConstraint
# проверку, читаем запрос, смотрим, от кого он и решаем: пускать или нет.
# "user_id" - помещен либо в сессию, либо в зашифрованные куки если юзер поставил галочку
# "запомнить меня" (см. authentication.rb)
# request.cookie_jar.encrypted[:user_id] - дешифровка куки
class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    # является ли найденный юзер админом
    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  # Смонтировать маршрут Sidekiq::Web , по какому адресу он будет доступен ('/sidekiq'),
  # т.е. подрубаем интерфейс sidekiq по адресу '/sidekiq'
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end
  # например localhost/ru/questions, localhost/en/questions, localhost/questions
  # locale: /#{I18n.available_locales.join("|")}/ - проверка, что запрошенная локаль входит
  # в массив %i[en ru], а ("|") - "или" (локаль или такая, или такая.....)
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    # маршрут для сброса пароля (resource без s, т.к. не будем работать с id юзера)
    # new create - запросить инструкции для сброса пароля, edit update - сбросить
    resource :password_reset, only: %i[new create edit update]

    # create - будет проверять корректность введенных данных и пускать пользователя в систему
    # new - отображать форму для входа
    # destroy - позволить юзерам из системы выходить
    # при входе юзера в систему он создает новую сессия
    # Если хотим, чтоб не было никаких идентификаторов в маршрутах, пишем
    # "resource" а не "resources"
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    # не нужен маршрут "new", потому что форма рендериться на другой странице
    # и "show", поскольку не нужно показывать каждый вопрос на отдельной странице

    # resources :questions, only: %i[index new edit create update destroy show]

    # контроллер "questions" должен обрабатывать методом - "index"
    # Я хотел бы, чтобы при заходе на мой сайт пользователи писали к примеру "localhost/questions"
    # в своей адресной строке браузера. Нажатие enter и отправляется GEt запрос. Поэтому, как только придет
    # # GEt-запрос с адресом /questions, тогда направляй его на контроллер "questions"
    # get '/questions', to: 'questions#index'

    # # маршрут к созданию нового вопроса пользователем и метод "new"
    # get '/questions/new', to: 'questions#new'

    # # :id - переменная поля (идентификатор вопроса), edit - редактир.запись
    # get '/questions/:id/edit', to: 'questions#edit'

    # # маршрут к месту создания вопроса
    # post '/questions', to: 'questions#create'

    # корневой маршрут
    root 'pages#index'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Commentable
  include Authorship
  # создается отношение на стороне Question
  # если удаляется вопрос, то и все зависимые ответы
  has_many :answers, dependent: :destroy
  belongs_to :user

  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  # Логика проверки двух полей в БД
  # Чтобы не отправляли пустые вопросы, используем проверки, чтобы
  # был title и body, т.е. true. И минимальная длина не меньше 2
  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

  # scope - метод класса в RoR, который можно вызвать, т.е "scope :all_by_tags"
  # равносильно "all_by_tags(params[:tag_ids])", т.е. можно было написать
  # "def self.all_by_tags", разницы нет.
  # С помощью scope мы можем выбирать определенные записи по каким то критериям
  scope :all_by_tags, lambda { |tags|
    questions = includes(:user)
    questions = if tags
                  # связка в SQL с таблице тегов, где теги - это "tags", только если он существует
                  questions.joins(:tags).where(tags: tags).preload(:tags)
                else
                  questions.includes(:question_tags, :tags)
                end
    # либо выбираем все вопросы
    questions.order(created_at: :desc)
  }
end

app/controllers/questions_controller.rb
  # frozen_string_literal: true

  # rubocop:disable all
class QuestionsController < ApplicationController
  include QuestionsAnswers
  # Проверка, что юзер вошел в систему во всех случаях, кроме когда он
  # просматривает все вопросы или конкретный вопрос. Но если он пытается создать
  # вопрос или отредактировать, то мы требуем, чтобы он вошел в систему, иначе
  # мы не может проверить его права доступа.
  before_action :require_authentication, except: %i[show index]
  before_action :set_question!, only: %i[show destroy edit update]
  # Проверяем, имеет ли пользователь право на выполнение запрошенного действия
  before_action :authorize_question!
  # М-д "verify_authorized" доступен из Pundit и он проверит, что мы в нашем "before_action"
  # проверили права доступа. Если проверены не были, то выскочит ошибка. Проверка во всех
  # действиях контроллера
  after_action :verify_authorized

  # информация на экран о конкретной записи
  def show
    load_question_answers
  end

  # удалить вопрос
  def destroy
    @question.destroy
    respond_to do |format|
      format.html do
        flash[:success] = t('.success')
        redirect_to questions_path, status: :see_other
      end

      format.turbo_stream { flash.now[:success] = t('.success') }
    end
  end

  # редактировать вопрос
  def edit; end

  # обновить наш вопрос с новыми параметрами
  def update
    if @question.update question_params
      respond_to do |format|
        format.html do
          flash[:success] = t('.success')
          redirect_to questions_path
        end

        format.turbo_stream do
          @question = @question.decorate
          flash.now[:success] = t('.success')
        end
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # Вытащить из БД все вопросы,отсортировать и сохранить в переменную @questions
  # page - разбивает коллекцию по страницам
  # для того, чтобы определить, какую страницу хочет запросить пользователь
  # используется параметр "page"
  # def index
  #   @questions = Question.order(created_at: :desc).page params[:page]
  # end

  # pagy - выдаст объект, с помощью которого отрисовывается навигация и выдаст
  # вопросы, которые уже разбиты по страничкам
  def index
    @tags = Tag.where(id: params[:tag_ids]) if params[:tag_ids]
    @pagy, @questions = pagy Question.all_by_tags(@tags), link_extra: 'data-turbo-frame="pagination_pagy"'
    @questions = @questions.decorate
  end

  # инстанцируется новая запись пользователем
  def new
    # переменная образца класса Question
    @question = Question.new
  end

  # создается образец класса Question с параметрами "question_params"
  def create
    # Для текущего пользователя построить новый вопрос с такими то параметрами
    @question = current_user.questions.build question_params
    # если вопрос сохранить удалось, перенаправить пользователя по пути /questions
    # приходит ответ от сервера 302 "переходи на другую страницу"
    if @question.save
      respond_to do |format|
        format.html do
          flash[:success] = t('.success')
          redirect_to questions_path
        end

        format.turbo_stream do
          @question = @question.decorate
          # now - чтоб при перезагрузке страницы не появлялся
          flash.now[:success] = t('.success')
        end
      end
    else
      # нужно отрендерить еще раз представление "new.html.erb"
      render :new
    end
  end

  private

  # из присланных параметров найти вопрос и достать только title и body
  # "tag_ids: []" - т.е. на данной позиции может идти целый массив из "id",
  # и каждый id представляет собой один тег
  def question_params
    params.require(:question).permit(:title, :body, tag_ids: [])
  end

  def set_question!
    @question = Question.find params[:id]
  end

  # Нужно авторизовать конкретный вопрос или просто использовать модель. Т.е. если
  # вопрос есть, то мы делаем проверку относительно него. Если вопроса нет, то мы говорим
  # что юзер пытается делать что-то относительно ресурса вопроса.
  # Метод "authorize" доступен из Pundit, потому что в ApplicationController заинклюдили
  # concern "Authorization", а этот concern в свою очередь инклюдит Pundit
  def authorize_question!
    authorize(@question || Question)
  end
end
# rubocop:enable all

app/views/questions/_form.html.erb
<%= turbo_frame_tag question do %>
  <%= form_with model: question do |f| %>
    <%= render 'shared/errors', object: question %>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :title %>
      </div>

      <div class="col-sm-10">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :body %>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :body, class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :tags %>
      </div>

      <%# collection_select - хэлпер-дропдаун, который позволяет выбирать тэг. Но т.к. в нашем случае
              у одного вопроса может быть много тегов, то "multiple: true".
              :tag_ids - название поля, tags - коллекция теговб id - метод, испольуемый при отображении идентификаторов
              в разметке, title - метод для отображения лэйблов, то, что будет видеть юзер.%>
      <div class="col-sm-10">
        <%= f.collection_select :tag_ids, question.tags, :id, :title, {}, multiple: true,
          class: 'js-multiple-select', data: {'ajax-url': '/api/tags'} %>
      </div>
    </div>

    <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/questions/_question.html.erb
<%= turbo_frame_tag question do %>
  <article class="card my-3">
    <section class="card-header">
      <%= question.user.gravatar %>
      <%= question.user.name_or_email %>
    </section>

    <div class="card-body">
      <h4><%= link_to question.title, question_path(question),
      # перерисовать всю страницу и выйти на страницу конкретного вопроса
        data: {turbo_frame: '_top'} %></h2>

      <section class="card-text">
        <%= tag.time datetime: question.formatted_created_at do %>
          <small><%= question.formatted_created_at %></small>
        <% end %>
        <%# рендер тегов для конкретного вопроса %>
        <div class="my-2">
          <%= render question.tags %>
        </div>

        <p class="my-2">
          <%= sanitize question.body %>
        </p>
      </section>

      <% if policy(question).edit? %>
        <%= link_to t('global.button.edit'), edit_question_path(question), class: 'btn btn-secondary' %>
      <% end %>
      <% if policy(question).destroy? %>
        <%= link_to t('global.button.delete'), question_path(question), class: 'btn btn-danger',
          data: {turbo_method: :delete, turbo_confirm: t('global.dialog.you_sure')} %>
      <% end %>
    </div>
  </article>
<% end %>

app/views/questions/create.turbo_stream.erb
<%# куда нужно отправить только что созданный вопрос
prepend (м-д турбо-стрим) - засунет html render(@question) и засунет его
в элемент с таким то id ('questions')%>
<%= turbo_stream.prepend 'questions', render(@question) %>
<%= prepend_flash %>

app/views/questions/destroy.turbo_stream.erb
<%= turbo_stream.remove @question %>
<%= prepend_flash %>

app/views/questions/edit.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t '.title' %></h1>

<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<section class="mb-5">
  <h2><%= t '.search_by_tags' %></h2>

  <%# отправляем форму на страницу "questions_path" - get-запрос%>
  <%= form_with url: questions_path, method: :get do |f| %>
    <div class="mb-3">
      <%# {selected: params[:tag_ids]} - т.е. когда форма будет отправлена и страница перерисуется,
                              		в этой форме выбирутся все те теги, которые выбраны для построения этого поиска.
                              		required: true - чтоб эту форму нельзя было отправить пустой %>
      <%# ajax — асинхронный запрос(чтобы теги подтягивались по необходимости) отправляться сюда "/api/tags"
                        и чтобы отсюда вытаскивать только те теги,
                        					которые подходят под критерии пользователя, т.е. исходя из того, что юзер напечатает %>
    <%= f.collection_select :tag_ids, (@tags || []), :id, :title, {selected: params[:tag_ids]},
        multiple: true, required: true,
        class: 'js-multiple-select js-ajax-select w-100', data: {'ajax-url': '/api/tags'} %>
    </div>

  <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
<% end %>
</section>

<%# для нового вопроса question нет, поэтому передаем название политики %>
  <% if policy(:question).new? %>
  <%= link_to t('.new'), new_question_path,
   class: 'btn btn-primary btn-lg mb-3',
    data: { turbo_frame: dom_id(Question.new) } %>

  <%# Вывести на странице новый турбо-фрейм тег Question.new
    Question.new - объект, но основе которого мы генерируем идентификатор турбо-фрейма
    turbo_frame_tag с помощью метода dom_id. Контент со страницы new_question_path вставлен будет в
    турбо-фрейм Question.new %>
    <div class="my-3"> <%= turbo_frame_tag Question.new %>
  </div>
<% end %>

<%# данная навигация показывается в том случае, если количество страниц больше 1 %>
<%# pagination @questions %>
<%= turbo_frame_tag 'pagination_pagy' do %>
  <%= pagination @pagy %>

  <%= turbo_frame_tag 'questions' do %>
    <%= render @questions %>
  <% end %>

  <%# данная навигация показывается в том случае, если количество страниц больше 1 %>
  <%# pagination @questions %>
  <%= pagination @pagy %>
<% end %>

app/views/questions/new.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<% provide :page_title, @question.title %>
<% currently_at t('menu.questions') %>

<article class="mb-3">
  <%= render @question %>
</article>

<%= render 'comments/commentable', commentable: @question, comment: @comment %>

<h2 class="mb-3"><%= t '.write_answer' %></h2>

<%= render 'answers/form' %>

<h2 class="mt-5 mb-3"><%= t '.answers' %></h2>

<%# данная навигация показывается в том случае, если количество страниц больше 1 %>
<%# pagination @questions %>
<%= pagination @pagy %>

<%= turbo_frame_tag 'answers' do %>
  <%= render partial: 'answers/answer', collection: @answers,
      as: :answer, locals: {question: @question} %>
<% end %>

<%# данная навигация показывается в том случае, если количество страниц больше 1 %>
<%# pagination @questions %>
<%= pagination @pagy %>

app/views/questions/update.turbo_stream.erb
<%# Не добавляем новый вопрос (prepend), а заменяем существующий
replace, а в качестве айдишника сам вопрос @question и рендерим %>
<%= turbo_stream.replace @question, render(@question) %>
<%= prepend_flash %>