config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

# класс "Ограничение". М-д "matches" принимает запрос, который был отправлен
# на адрес '/sidekiq'. Приходит на этот адрес запрос, перенаправлем в AdminConstraint
# проверку, читаем запрос, смотрим, от кого он и решаем: пускать или нет.
# "user_id" - помещен либо в сессию, либо в зашифрованные куки если юзер поставил галочку
# "запомнить меня" (см. authentication.rb)
# request.cookie_jar.encrypted[:user_id] - дешифровка куки
class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    # является ли найденный юзер админом
    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  # Смонтировать маршрут Sidekiq::Web , по какому адресу он будет доступен ('/sidekiq'),
  # т.е. подрубаем интерфейс sidekiq по адресу '/sidekiq'
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end
  # например localhost/ru/questions, localhost/en/questions, localhost/questions
  # locale: /#{I18n.available_locales.join("|")}/ - проверка, что запрошенная локаль входит
  # в массив %i[en ru], а ("|") - "или" (локаль или такая, или такая.....)
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    # маршрут для сброса пароля (resource без s, т.к. не будем работать с id юзера)
    # new create - запросить инструкции для сброса пароля, edit update - сбросить
    resource :password_reset, only: %i[new create edit update]

    # create - будет проверять корректность введенных данных и пускать пользователя в систему
    # new - отображать форму для входа
    # destroy - позволить юзерам из системы выходить
    # при входе юзера в систему он создает новую сессия
    # Если хотим, чтоб не было никаких идентификаторов в маршрутах, пишем
    # "resource" а не "resources"
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    # не нужен маршрут "new", потому что форма рендериться на другой странице
    # и "show", поскольку не нужно показывать каждый вопрос на отдельной странице

    # resources :questions, only: %i[index new edit create update destroy show]

    # контроллер "questions" должен обрабатывать методом - "index"
    # Я хотел бы, чтобы при заходе на мой сайт пользователи писали к примеру "localhost/questions"
    # в своей адресной строке браузера. Нажатие enter и отправляется GEt запрос. Поэтому, как только придет
    # # GEt-запрос с адресом /questions, тогда направляй его на контроллер "questions"
    # get '/questions', to: 'questions#index'

    # # маршрут к созданию нового вопроса пользователем и метод "new"
    # get '/questions/new', to: 'questions#new'

    # # :id - переменная поля (идентификатор вопроса), edit - редактир.запись
    # get '/questions/:id/edit', to: 'questions#edit'

    # # маршрут к месту создания вопроса
    # post '/questions', to: 'questions#create'

    # корневой маршрут
    root 'pages#index'
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Commentable
  include Authorship
  # Ответ принадлежит и вопросу и юзеру
  belongs_to :question
  belongs_to :user

  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
  # frozen_string_literal: true

  # rubocop:disable all
class AnswersController < ApplicationController
  include QuestionsAnswers
  # модуль для якорей
  include ActionView::RecordIdentifier
  # и для create и для destroy
  # порядок action важен: сначала идет вопрос, потом ответ
  before_action :set_question!
  before_action :set_answer!, except: :create
  before_action :authorize_answer!
  after_action :verify_authorized

  def create
    # создаваемые ответы привязываем к вопросу
    @answer = @question.answers.build answer_create_params
    @answer = @answer.decorate
    if @answer.save
      respond_to do |format|
        format.html do
          flash[:success] = t '.success'
          # переводит пользователя на машрут, который заново обрабатывается
          # обращается к нужному представлению "show", и все перем-е устанавливаются
          redirect_to question_path(@question)
        end

        format.turbo_stream do
          flash.now[:success] = t '.success'
        end
      end
    else
      load_question_answers(do_render: true)
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html do
        flash[:success] = t '.success'
        redirect_to question_path(@question), status: :see_other
      end

      format.turbo_stream { flash.now[:success] = t('.success') }
    end
  end

  def edit; end

  def update
    if @answer.update answer_update_params
      respond_to do |format|
        format.html do
          flash[:success] = t '.success'
          # + переброска к конкретному ответу на странице вопроса
          # <%= tag.article class: 'mb-3 card', id: dom_id(answer) do %> <% end %>
          redirect_to question_path(@question, anchor: dom_id(@answer))
        end

        format.turbo_stream do
          @answer = @answer.decorate
          flash.now[:success] = t '.success'
        end
      end
    else
      render :edit
    end
  end

  private

  # в параметры для создания ответа юзером добавлен параметр "user_id"
  def answer_create_params
    params.require(:answer).permit(:body).merge(user_id: current_user.id)
  end

  def answer_update_params
    params.require(:answer).permit(:body)
  end

  # метод, который может вернуть ошибку
  def set_question!
    # проверить,что вопрос для которого пишется ответ,существует
    @question = Question.find params[:question_id]
  end

  def set_answer!
    # ":id" => @answers (id ответа)
    @answer = @question.answers.find params[:id]
  end

  def authorize_answer!
    authorize(@answer || Answer)
  end
end
# rubocop:enable all

app/views/answers/_answer.html.erb
<%= turbo_frame_tag answer do %>
  <%= tag.article class: 'my-3 card border-0 border-top' do %>
    <div class="row g-0">
      <div class="col-sm-auto text-sm-center align-self-center">
        <%= answer.user.gravatar size: 50, css_class: 'd-block' %>
        <%= answer.user.name_or_email %>
      </div>
      <div class="col-sm">
        <div class="card-body">
          <section class="card-text mb-3">
            <div class="col-sm-9">
              <small><time datetime="<%= answer.formatted_created_at %>">
                <%= answer.formatted_created_at %>
              </time></small>

              <div class="mt-2">
                <%= sanitize answer.body %>
              </div>
            </div>
          </section>

          <% if policy(answer).edit? %>
            <%= link_to t('global.button.edit'), edit_question_answer_path(question, answer),
              class: 'btn btn-info btn-sm' %>
          <% end %>
          <% if policy(answer).destroy? %>
            <%= link_to t('global.button.delete'), question_answer_path(question, answer), class: 'btn btn-danger btn-sm',
              data: {turbo_method: :delete, turbo_confirm: t('global.dialog.you_sure')} %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <%= render 'comments/commentable', commentable: answer, comment: @comment %>
<% end %>
<%# идентификатор comment_form, answer и идент-р ответа%>

app/views/answers/_form.html.erb
<%= turbo_frame_tag @answer do %>
  <%= form_with model: [@question, @answer] do |f| %>
    <%= render 'shared/errors', object: @answer %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :body %>
      </div>

    <%# required: true  - тело должно быть заполнено %>
      <div class="col-sm-10">
        <%= f.text_area :body, class: 'form-control', required: true %>
      </div>
    </div>

  <%# <%= f.submit "Submit answer!", class: 'btn btn-primary' %>
    <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/answers/create.turbo_stream.erb
<%= turbo_stream.prepend "answers", render(@answer, question: @answer.question) %>
<%= prepend_flash %>

app/views/answers/destroy.turbo_stream.erb
<%= turbo_stream.remove @answer %>
<%= prepend_flash %>

app/views/answers/edit.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1><%= t '.title' %></h1>

<%= render 'form' %>

app/views/answers/update.turbo_stream.erb
<%= turbo_stream.replace @answer, render(@answer, question: @answer.question) %>
<%= prepend_flash %>